# ansible-playbook roboshop.yaml -e "component=mongodb"   
                          # if we use TERRAFORM then ROBOSHOP.YAML will RUN FIRST 
- name: configure "{{ component }}" server
  hosts: "{{ component }}"
  connection: local
  become: yes
  roles:
  - "{{ component }}"